[package]
name = "partiql"
version = "0.1.0"
edition = "2018"
authors = ["FUKUDA Yutaro <fuyutarow@gmail.com>"]

[lib]
name = "partiql"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version="0.13.2", features=["extension-module"] }

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]
